name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for pointing out the issue. I will try to fix it as soon as possible."
        pr-message: "Thanks for submitting the pull request. I will review the changes and approve (if changes are legit) as soon as possible."
